# Generated by Django 6.0.1 on 2026-05-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
    ]
