# Generated by Django 6.0.1 on 2026-05-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registros',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
